server :
  port : 8080
spring:
  output:
    ansi:
      enabled : always

  profiles:
    active: local
  redis:
    host: localhost
    port: 6379

  #  datasource :
  #    url : jdbc:h2:tcp://localhost/~/ideazip
  #    username : sa
  #    password : sa
  #    driver-class-name: org.h2.Driver
  jpa :
    hibernate :
      ddl-auto: create
    properties:
      hibernate:
        show_sql : true
        format_sql : true
        default_batch_fetch_size : 100
    open-in-view: false

  devtools:   # 정적자원 캐시사용안함=> 새로고침시 바로바로,   but 실제서버운영시 캐시 사용해야된다
    livereload :
      enabled : true
    freemarker:
      cache: false
    restart:
      enabled: false
  thymeleaf:
    cache: false

